### ISSUE TITLE
Some notes are not getting synced

### ISSUE THREAD

**Issue by vginer** [ryanpcmcquen/inkdrop_plain_text_backups#4]
I just installed this plugin in Inkdrop (last version for Windows OS).

Some of my notes are not appearing as plain-text .MD files at the `PLAIN_TEXT` folder (or its subfolders).

Are there any known reasons that may trigger this issue?

Please, let me know whether you need more information or I should post this elsewhere.

Looking forward to your answer,

--
vicent

**Comment by ryanpcmcquen** [comment]
How many notes do you have? Try closing and relaunching the app, that _should_ do a full sync.

If you are comfortable with it, open the dev tools and see if the console has anything in it.

**Comment by vginer** [comment]
I have a total of 33 notes in Inkdrop, but many of them are not getting synced in the `PLAIN_TEXT` folder. See, for instance, my 'AGENDA' notebook and the `AGENDA` folder in `PLAIN_TEXT` (see attached files).

![image](https://user-images.githubusercontent.com/1314764/119838957-19e2cb00-bf04-11eb-98c4-27c2d2044f42.png)

![image](https://user-images.githubusercontent.com/1314764/119839052-29621400-bf04-11eb-8843-f51275173a26.png)

I already tried closing and relaunching the app, several times. There is even one .MD file that has disappeared after that (I had 3 files in the `AGENDA` folder, and now I have only two of them).

I am not able to figure out the reason why some files are getting synced and others not.

Could you please tell me what de 'dev tools' means and how to open it?

**Comment by ryanpcmcquen** [comment]
There should be an option in one of the menus for opening or viewing the developer tools.

What are you using for syncing?

Are there any content differences between notes that sync and those that don't (title, note content, special characters)?

**Comment by vginer** [comment]
I am syncing using the default setting: Inkdrop Sync Service. As for the backup, I am just using your plugin.

As for the contents or special characters, I am not sure. I am not able to figure out a pattern here.

When I open the developer tools, I get this:

![image](https://user-images.githubusercontent.com/1314764/119900293-a0b79800-bf44-11eb-8dce-0ae9a8b45207.png)

Should I try 'Rebuild FTS Index'??

**Comment by ryanpcmcquen** [comment]
Do you have 'files on demand' turned on for OneDrive? If so, try turning it off.

**Comment by vginer** [comment]
No, I don't have 'files on demand' enabled.

![image](https://user-images.githubusercontent.com/1314764/119938443-b6e94680-bf8c-11eb-8440-76cef294d8a9.png)

**Comment by ryanpcmcquen** [comment]
Thank you for checking. Try deleting the `PLAIN_TEXT` folder and relaunching Inkdrop, open the dev tools again and paste the console output here.

**Comment by vginer** [comment]
I did what you asked for.

Here you have the results (two screenshots):

![image](https://user-images.githubusercontent.com/1314764/120006353-1cfbbb00-bfd9-11eb-8ec0-920bedef66b4.png)

![image](https://user-images.githubusercontent.com/1314764/120006441-2dac3100-bfd9-11eb-9a35-075a67810c1f.png)

The `PLAIN_TEXT` folder has been created again, with the same missing .MD files than before.

**Comment by ryanpcmcquen** [comment]
What if you remove the `|` character from the title of all notes? Does it work then?

**Comment by ryanpcmcquen** [comment]
That character is not allowed in OneDrive:
https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidcharacters

You should check all your titles for other invalid characters.

**Comment by vginer** [comment]
OK... I changed backups to a local folder, uninstalled your plugin, restarted Inkdrop, reinstalled your plugin, and.... the problem persists!   :/  because Windows 10 does not allow file names that include that very same list of invalid characters (see an screenshot below). The console in Inkdrop shows the same problem as before.

So, the solution is clear: I should avoid certain characters in the title of notes and in the name of notebooks.

Thank you for your help and your patience!

![image](https://user-images.githubusercontent.com/1314764/120022145-440fb800-bfec-11eb-934d-a029ffe1f207.png)

**Comment by ryanpcmcquen** [comment]
> OK... I changed backups to a local folder, uninstalled your plugin, restarted Inkdrop, reinstalled your plugin, and.... the problem persists! :/ because Windows 10 does not allow file names that include that very same list of invalid characters (see an screenshot below). The console in Inkdrop shows the same problem as before.
> 
> So, the solution is clear: I should avoid certain characters in the title of notes and in the name of notebooks.
> 
> Thank you for your help and your patience!
> 
> ![image](https://user-images.githubusercontent.com/1314764/120022145-440fb800-bfec-11eb-934d-a029ffe1f207.png)

Yay! Glad it all worked out. File names are tough, I have hit my own issues. Inkdrop used to use `:` characters in its own backups and it was a mess!
