### ISSUE TITLE
Some notebook folders not being created, using "undefined" instead

### ISSUE THREAD

**Issue by guiix-code** [ryanpcmcquen/inkdrop_plain_text_backups#5]
First up, nice plugin :) Thanks for making this.

I have an issue where 3 notebook folders aren't being created, instead all notes for those 3 folders are being placed into "undefined" folder instead. 6 other notebook folders work fine. I cannot discern any particular difference between them or their notes. If I move a note (in Inkdrop) from a non-working notebook to a working notebook, then the note backs up to the correct folder. But moving it back to the original notebook means the note backs up into the "undefined" folder. All folder names are plain english, no characters or anything unusual.

Creating the folders manually also does not work, nor manually moving the files from the "undefined" folder into the correct folder and then restarting inkdrop, that too doesn't work.

Doing an export of all notes (File -> Export -> All Notes) does create and use all the correct folders.

**Comment by ryanpcmcquen** [comment]
What are the folder names? What operating system?

**Comment by guiix-code** [comment]
OSX 11.
Names "Travel", "House" and "General" aren't working.

**Comment by ryanpcmcquen** [comment]
Are there any others with the same name?

**Comment by guiix-code** [comment]
No other folders nor files with the same name.

Another odd feature, after removing the plugin, removing the PLAIN_TEXT directory, and then re-installing the plugin, is that only some files in each folder are being created. Other files will save to PLAIN_TEXT once I edit and re-save them in Inkdrop.

**Comment by ryanpcmcquen** [comment]
Try completely closing and relaunching the app.

**Comment by ryanpcmcquen** [comment]
Were these folders ever in the 'Trash'?

**Comment by ryanpcmcquen** [comment]
Are you using any syncing service like Dropbox?

**Comment by guiix-code** [comment]
None went into Trash no. 
Have tried closing app, removing PLAIN_TEXT directory, and relaunching (again where not all notes even in working directories will appear until they are next saved).
No sync services, using a plain directory in home directory.

**Comment by guiix-code** [comment]
Have also tried removing inkdrop's configuration directory and doing a fresh install. Still the same issue.

**Comment by ryanpcmcquen** [comment]
Any errors in the console?

**Comment by guiix-code** [comment]
No errors. Only some warnings about inkdrop's missing sourcemaps.

**Comment by ryanpcmcquen** [comment]
If you're comfortable with the debugger, you could put a breakpoint on the file writes and see what the data looks like.

**Comment by guiix-code** [comment]
Found issue.
When you call .all() on the database, there is a default page limit of 20.

    inkdrop.main.dataStore.getLocalDB().notes.all()

You'll need to use:

    inkdrop.main.dataStore.getLocalDB().notes.all({limit: 9999})

**Comment by ryanpcmcquen** [comment]
Weird! Is that new? I don't remember paging in the past. Good find!

**Comment by ryanpcmcquen** [comment]
Closed in:
https://github.com/ryanpcmcquen/inkdrop_plain_text_backups/releases/tag/v0.7.1.
