### ISSUE TITLE
Not backing up one of my notebooks

### ISSUE THREAD

**Issue by raelb** [ryanpcmcquen/inkdrop_plain_text_backups#6]
Hi,
the plugin fails to backup one of my notebooks: ("Google --" and subfolder...)
![image](https://user-images.githubusercontent.com/13108198/148261784-63d80180-7039-4065-a944-e7fa135917d5.png)

Instead, the notes it contains are moved into an "undefined" folder.
![image](https://user-images.githubusercontent.com/13108198/148261830-bb89c722-911f-4a5b-b885-f61d416a9630.png)

Moreover, any subfolders are also not working, and their notes, are placed into the same "undefined" folder.

Not sure why these notebooks are not showing up at all in the DATA MAP json file:
![image](https://user-images.githubusercontent.com/13108198/148262151-6f62690c-9580-4c3c-94cc-ee93709400fb.png)

![image](https://user-images.githubusercontent.com/13108198/148262331-46622e8f-9e56-4de7-8d8a-e157730a0727.png)

One note: After installing the plugin, and then starting Inkdrop, the "Google" notebook did not contain any notes. When I subsequently added a note, the plugin did not pick it up.

**Comment by ryanpcmcquen** [comment]
Would you try copying the exact text of that folder name and creating a new folder in Explorer with the copied contents?

**Comment by raelb** [comment]
I just noticed, that there was a similar (if not identical) closed issue.

![image](https://user-images.githubusercontent.com/13108198/148264182-94c63488-6871-4e76-8797-7c2222a0474a.png)

Inkdrop detects the latest version as 0.7.0, not 0.7.1?

**Comment by raelb** [comment]
If I copy over the one mod ({limit: 999999 }), then it works fine. It seems the issue is detecting the latest version of the plugin..

**Comment by ryanpcmcquen** [comment]
Ah, @raelb I just re-published that version, can you see if an update is available?

**Comment by raelb** [comment]
Thanks, it is working now

**Comment by ryanpcmcquen** [comment]
Thanks for the report!
