### ISSUE TITLE
Inconsistent results when renaming notebooks

### ISSUE THREAD

**Issue by raelb** [ryanpcmcquen/inkdrop_plain_text_backups#7]
I seem to get inconsistent results when renaming notebooks. Sometimes it works fine, each time. Sometimes it only works the first time, but not after that.
Also, perhaps a related issue: If I create a new notebook, then add a note to it. The plugin creates a folder "undefined" and saves the note to that. Then if I bring up the preferences dialog, then it creates the folder correctly. If I rename the folder, nothing happens. Then when I bring up the preferences dialog, it creates the folder with the new name. (So now there is the old folder name, and a new folder name..)
I wonder if you can reproduce any of this?
I'm using Inkdrop 5.4.3, and I'm on Windows 10.

**Comment by ryanpcmcquen** [comment]
Renames are tricky, and sometimes Inkdrop reports a folder as 'undefined' in transition states (it also does this for the trash folder). The best way to ensure this works is to force the save of a note after renaming a folder.
